package com.jorgegarcia.airvisual.model;

public enum MessageType {
	LAUNCH,HELP,LAUNCH_SHORT,GOODBYE,ERROR,NO_ADDRESS,NO_NEAR_STATION,NO_INTENT_RECOGNIZED,
	REPROMPT_SOMETHING_ELSE, REPROMPT_GET_DETAILS,EXCELLENT_AIR_QUALITY,GOOD_AIR_QUALITY,
	REGULAR_AIR_QUALITY,BAD_AIR_QUALITY,HAZARD_AIR_QUALITY,AIR_QUALITY_IN, NO_GEOLOCATION,NO_PERMISSIONS;

}
